# Generated by Django 5.1.7 on 2025-03-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('ph', models.FloatField()),
                ('ec', models.FloatField()),
                ('oc', models.FloatField()),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.FloatField()),
                ('b', models.FloatField()),
                ('s', models.FloatField()),
                ('zn', models.FloatField()),
                ('cu', models.FloatField()),
                ('fe', models.FloatField()),
                ('mn', models.FloatField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
