# Generated by Django 5.1.7 on 2025-03-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcard',
            name='is_published',
        ),
        migrations.AddField(
            model_name='healthcard',
            name='mobile_number',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcard',
            name='publish',
            field=models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('SMS', 'Short Messaging Service'), ('MMS', 'Multimedia Message')], default='WhatsApp', max_length=20),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='remarks',
            field=models.CharField(default='tes', max_length=150),
            preserve_default=False,
        ),
    ]
